@startuml SteamInvite

'テーマ

!theme sunlust from https://raw.githubusercontent.com/plantuml/plantuml/master/themes


'定義
actor ユーザー
participant デーモン
box サーバー
  participant BOT
  database DB
end box


'処理

group デーモンを起動

ユーザー -> デーモン: exeを起動
activate デーモン

デーモン -> デーモン: UUIDを読み込み or 生成して保存

デーモン -> BOT: WebSocket接続 (UUIDを送信)
activate BOT #Orange
note right: WebSocket接続

BOT -> BOT: UUID→Socketを紐付け
BOT --> デーモン: WebSocket初期化完了
デーモン -> ユーザー: 起動完了通知
note right: 「/steam setup UUID と入力してください」と表示

end


group Discord上で デーモンとユーザーを紐付け

ユーザー -> BOT: 「/steam setup UUID」コマンド実行
activate BOT

BOT -> DB: DiscordユーザーID→UUIDを紐付け
DB --> BOT
BOT --> ユーザー: 「セットアップ完了」
deactivate BOT

end


group Discord上で 招待パネル作成

ユーザー -> BOT:「/steam invite」コマンド実行
activate BOT
BOT -> DB: DiscordユーザーID→UUIDを取得
DB --> BOT
BOT -> BOT: UUID->Socket情報取得
BOT -> デーモン: Steamゲーム情報を取得リクエスト
デーモン --> BOT: Steamゲーム情報を取得レスポンス

BOT --> ユーザー: 招待リンク取得ボタン表示\nSteamゲーム情報を表示
deactivate BOT

end


group Discord上で 招待リンク取得

ユーザー -> BOT: 招待リンク取得ボタンクリック
activate BOT
BOT -> DB: DiscordユーザーID→UUIDを取得
DB --> BOT
BOT -> BOT: UUID->Socket情報取得
BOT -> デーモン: 招待リンク取得リクエスト
デーモン --> BOT: 招待リンク取得レスポンス

BOT --> ユーザー: 招待リンク表示
deactivate BOT

end


group デーモンを終了

ユーザー -> デーモン: exeを終了
デーモン -> BOT: WebSocket切断
BOT -> BOT: UUID→Socket紐づけ解除
deactivate BOT

デーモン --> ユーザー: 終了通知
deactivate デーモン

end

@enduml